# build environment
FROM node:18.19.0-alpine3.18 as build

RUN apk update
RUN apk add --no-cache git

RUN mkdir /code
WORKDIR /code

ARG NODE_ENV

COPY . ./
RUN npm i --silent
RUN npm run build

# production environment
FROM nginx:stable-alpine

COPY --from=build /code/dist /usr/share/nginx/html

# nginx config
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80